[package]
name = "tickets-ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "tickets_ui"
crate-type = ["cdylib"]

[dependencies]
packr-guest = { version = "0.24", features = ["derive"] }
packr-abi = { version = "0.24", default-features = false }
theater-guest = { git = "https://github.com/colinrozzi/theater", rev = "d1a9f270bdff0e96548e09bdbda6973292c21477" }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
